### ISSUE TITLE
Cannot get manual_page_break_after_row to work

### ISSUE THREAD

**Issue by meefen** [ulyngs/pagedownCV#6]
Thanks for the nice work!

Regarding the issue with the row issue. I could not get the `manual_page_break_after_row` function to work. 

What should I put for the `text_to_detect` parameter? I tried a few things but none seemed to work for me.

Thank you!

**Comment by ulyngs** [comment]
Reinstall the `pagedownCV`, then have a look at the example (`?manual_page_break_after_row`):

`text_to_detect` is some string of text inside the row that you want to add a break after

<img width="698" alt="image" src="https://user-images.githubusercontent.com/23137032/201332940-b10a9e8c-0f82-4c5d-a64e-059ec290aa94.png">
